// Isometric plug-in for WADE (version 1.1) - Copyright Clockwork Chilli ltd 2012-2014 - all rights reserved. You must obtain a valid license at www.clockworkchilli.com to redistribute this file 
Wade_iso=function(){var b=this,c=1.018,a=30,d=25,e={},m=[],s,g,n,j,k;this.init=function(f){(!wade.requireVersion||!wade.requireVersion("1.1"))&&alert("This version of wade.iso requires a newer version of WADE (1.1 or newer). Please upgrade at www.clockworkchilli.com");f=f||{};"number"==typeof f.tileScaleFactor&&(c=f.tileScaleFactor);"number"==typeof f.terrainLayerId&&(a=f.terrainLayerId);"number"==typeof f.objectsLayerId&&(d=f.objectsLayerId);f.dontClearCanvas&&wade.setCanvasClearing(a,!1);wade.setLayerSorting(d,
"bottomToTop");s=new SceneObject(0,TerrainBehavior,0,0);g=s.getBehavior();"object"==typeof f.tileSize&&(g.c_tileSize=wade.cloneObject(f.tileSize));"number"==typeof f.numCellsPerTile&&(g.c_numCellsPerTile=f.numCellsPerTile);if("object"==typeof f.numTiles)var t=f.numTiles.x,p=f.numTiles.z;wade.addSceneObject(s);this.gameObjects=[];this.gridObjects=[];this.collisionMap=[];m=[];j=f.movementDirection||"diagonal";k=y(j);var r=new Sprite(0,a);r.setSize(g.c_tileSize.x,g.c_tileSize.x);r.setDrawFunction(wade.drawFunctions.solidFill_("white"));
r.setRotation(Math.PI/4);var u=new Sprite(0,a);u.setSize(g.c_tileSize.x,g.c_tileSize.x);u.setDrawFunction(wade.drawFunctions.grid_(g.c_numCellsPerTile,g.c_numCellsPerTile,"black",2));u.setRotation(Math.PI/4);var w=new Sprite(0,a);w.setDrawFunction(function(){});var q=Math.ceil(g.c_tileSize.x*Math.sqrt(2));w.setSize(q,q);w.drawToImage("_wade_isoDefault",!0);r.drawToImage("_wade_isoDefault");u.drawToImage("_wade_isoDefault");r=new Sprite("_wade_isoDefault",a);r.setSize(g.c_tileSize.x,g.c_tileSize.y);
r.drawToImage("_wade_isoDefault",!0);w.drawToImage("_wade_isoGrid",!0);u.drawToImage("_wade_isoGrid");r=new Sprite("_wade_isoGrid",a);r.setSize(g.c_tileSize.x,g.c_tileSize.y);r.drawToImage("_wade_isoGrid",!0);if(f.map){n=f.map;e={};g.loadData_begin(n.data,i("terrain",f.callback));var h=n.data,z=f.callback,x,l=[],t={},A=0;if(h.gameObjects){for(f=0;f<h.gameObjectData.length;f++){for(p=0;p<h.gameObjectData[f].sprites.length;p++)for(u=0;u<h.gameObjectData[f].sprites[p].animations.length;u++)w=h.gameObjectData[f].sprites[p].animations[u].texture,
t[w]||(l.push(w),t[w]=1);if(p=h.gameObjectData[f].portraits)for(x in p)p.hasOwnProperty(x)&&!t[p[x]]&&(l.push(p[x]),t[p[x]]=1)}for(f=0;f<l.length;f++)wade.loadImage(l[f],function(){if(++A==l.length){if(h.gameObjects){s.getBehavior("TerrainBehavior");for(var f=0;f<h.gameObjects.length;f++)b.createObject(h.gameObjectData[h.gameObjects[f].templateId],h.gameObjects[f].gridCoords,h.gameObjects[f].instanceData)}i("objects",z)()}})}}else g.setNumTiles(t||1,p||1);wade.setMainLoopCallback(function(){for(var f=
m.length-1;0<=f;f--){var a=m[f],p=a.getPosition(),b=g.getCellCoordinates(p.x,p.y),t=g.getWorldCoordinates(b.x,b.z),r=p.x-t.x,t=p.y-t.y,c=g.c_cellSize.x/2,u=g.c_cellSize.y/2;("both"==j||"straight"==j)&&Math.abs(r)<wade.c_epsilon&&t*t>=u*u-wade.c_epsilon||Math.abs(t)<wade.c_epsilon&&r*r>=c*c-wade.c_epsilon||(v(a,b.x,b.z)?(a.iso.previousPosition.x=p.x,a.iso.previousPosition.y=p.y):(a.setPosition(a.iso.previousPosition),a.processEvent("onStuck",{})),a.iso.targetCoords&&(a.iso.targetCoords.x==b.x&&a.iso.targetCoords.z==
b.z)&&(a.iso.targetCoords=0,wade.removeObjectFromArray(a,m)))}},"_wade_isoMovingObjects")};this.getTileSize=function(){return wade.cloneObject(g.c_tileSize)};this.getValidMovementDirections=function(){return wade.cloneArray(k)};this.getCellSize=function(){return wade.cloneObject(g.c_cellSize)};this.getTileScaleFactor=function(){return c};this.getNumTiles=function(){return{x:g.numTilesX,z:g.numTilesZ}};this.getNumCells=function(){return{x:g.numTilesX*g.c_numCellsPerTile,z:g.numTilesZ*g.c_numCellsPerTile}};
this.getNumCellsPerTile=function(){return g.c_numCellsPerTile};this.getTileSprite=function(f,a){return g.tileSprites[f]&&g.tileSprites[f][a]};this.getTileData=function(f,a){return g.tileData[f]&&g.tileData[f][a]&&wade.cloneObject(g.tileData[f][a])};this.getTransitionSprite=function(f,a){return g.transitionSprites[f]&&g.transitionSprites[f][a]};this.getTransitionData=function(f,a){return g.transitionData[f]&&g.transitionData[f][a]&&wade.cloneObject(g.transitionData[f][a])};this.getDetailSprite=function(f,
a){return g.detailSprites[f]&&g.detailSprites[f][a]};this.getDetailData=function(f,a){return g.detailData[f]&&g.detailData[f][a]&&wade.cloneObject(g.detailData[f][a])};this.getTerrainLayerId=function(){return a};this.getObjectsLayerId=function(){return d};this.checkCollisionsAtCell=function(f,a){return!(!this.collisionMap[f]||!this.collisionMap[f][a])};this.setNumTiles=function(f,a){g.setNumTiles(f,a)};this.createObject=function(f,a,p){var f=f||{},p=p||{},a=a||{x:0,z:0},b=g.getWorldCoordinates(a.x,
a.z),c,e,q,h;if(!f.gridMap)if(f.gridSize){f.gridMap=[];for(c=0;c<f.gridSize.x;c++)for(e=0;e<f.gridSize.z;e++)f.gridMap.push({x:c,z:e})}else f.gridMap=[{x:0,z:0}];if(!f.collisionMap&&f.collisionSize){f.collisionMap=[];for(c=0;c<f.collisionSize.x;c++)for(e=0;e<f.collisionSize.z;e++)f.collisionMap.push({x:c,z:e})}var n=f.gridMap,j=f.collisionMap;if(j)for(c=0;c<j.length;c++)if(q=j[c].x+a.x,h=j[c].z+a.z,this.collisionMap[q]){if(this.collisionMap[q][h])return null}else this.collisionMap[q]=[];h=[];q=[];
if(f.sprites){j=jQuery.isArray(f.sprites)?f.sprites:[f.sprites];for(c=0;c<j.length;c++){var l=j[c],k=new Sprite(l.image,d);if(l.animations){var m=jQuery.isArray(l.animations)?l.animations:[l.animations];for(e=0;e<m.length;e++){var i=m[e],v=i.numCells||{x:1,y:1},v=new Animation(i.image,v.x,v.y,i.speed||30,i.looping,i.startFrame?i.startFrame:0,i.endFrame,i.autoResize,i.offset);i.blending&&v.setBlending(!0);k.addAnimation(i.name||"default",v)}k.playAnimation(m[0].name||"default")}e=l.size||k.getSize();
l.scale&&(e.x*=l.scale,e.y*=l.scale);k.setSize(e.x,e.y);k.setSortPoint((l.sortPoint?l.sortPoint.x:0)||0,(l.sortPoint?l.sortPoint.y:0.5)||0);h.push(k);q.push(l.offset?{x:(l.offset.x||0)*e.x,y:((l.offset.y||0)-0.5)*e.y}:{x:0,y:-e.y/2})}}if(c=f.behaviors){jQuery.isArray(c)||(c=[c]);for(j=0;j<c.length;j++)"string"==typeof c[j]&&typeof("function"==window[c[j]])&&(c[j]=window[c[j]])}b=new SceneObject(h,c,b.x,b.y,p.name);b.setSpriteOffsets(q);!f.dontAddToScene&&!p.dontAddToScene&&wade.addSceneObject(b);
b.iso={objectData:f,gridCoords:{x:a.x,z:a.z}};jQuery.extend(b,p);this.gameObjects.push(b);for(c=0;c<n.length;c++)q=n[c].x+a.x,h=n[c].z+a.z,this.gridObjects[q]||(this.gridObjects[q]=[]),this.gridObjects[q][h]||(this.gridObjects[q][h]=[]),this.gridObjects[q][h].push(b);if(f.collisionMap)for(c=0;c<f.collisionMap.length;c++)q=f.collisionMap[c].x+a.x,h=f.collisionMap[c].z+a.z,this.collisionMap[q]||(this.collisionMap[q]=[]),this.collisionMap[q][h]=b;b.getGridCoords=function(){return{x:this.iso.gridCoords.x,
z:this.iso.gridCoords.z}};return b};this.deleteObject=function(f){wade.removeObjectFromArray(f,this.gameObjects);var a,p,c,b=f.iso.objectData.collisionMap;if(b)for(a=0;a<b.length;a++)p=b[a].x+f.iso.gridCoords.x,c=b[a].z+f.iso.gridCoords.z,this.collisionMap[p]&&this.collisionMap[p][c]&&(this.collisionMap[p][c]=0);b=(b=f.iso.objectData.gridMap)||[{x:0,z:0}];for(a=0;a<b.length;a++)p=b[a].x+f.iso.gridCoords.x,c=b[a].z+f.iso.gridCoords.z,this.gridObjects[p]&&this.gridObjects[p][c]&&wade.removeObjectFromArray(f,
this.gridObjects[p][c]);wade.removeSceneObject(f)};this.deleteObjectByName=function(a){(a=wade.getSceneObject(a))&&this.deleteObject(a)};this.deleteObjectsInCell=function(a,b){if(!this.gridObjects[a])return!1;var c=this.gridObjects[a][b];if(!c)return!1;if(c.length){for(var g=c.length-1;0<=g;g--)this.deleteObject(c[g]);return!0}return!1};this.constrainCamera=function(f){"undefined"==typeof f&&(f=!0);f?wade.setMainLoopCallback(function(){var f=wade.getScreenWidth()/2,c=wade.getScreenHeight()/2,f={minX:-f,
minY:-c,maxX:f,maxY:c},c=wade.getLayer(a).screenBoxToWorld(f),f=(c.maxX-c.minX)/2,c=(c.maxY-c.minY)/2,b,d,e,j;b={x:0,y:0};d=g.getWorldCoordinates(0,g.numTilesZ*g.c_numCellsPerTile-1);d.x-=g.c_cellSize.x/2;e=g.getWorldCoordinates(g.numTilesX*g.c_numCellsPerTile-1,0);e.x+=g.c_cellSize.x/2;j=g.getWorldCoordinates(g.numTilesX*g.c_numCellsPerTile-1,g.numTilesZ*g.c_numCellsPerTile-1);j.y-=g.c_cellSize.y/2;var h=function(a,f){var c={};c.start=a;c.end=f;c.slope=(f.y-a.y)/(f.x-a.x);c.intercept=c.start.y-c.start.x*
c.slope;c.getX=function(a){return(a-this.intercept)/this.slope};return c},n;n=h(b,e);b=h(b,d);e=h(j,e);d=h(j,d);h=wade.getCameraPosition();h.y+c>-f/2?h.y=-f/2-c:h.y-c<j.y+f/2&&(h.y=j.y+f/2+c);h.x-=Math.max(0,h.x+f-Math.min(n.getX(h.y+c),e.getX(h.y-c)));h.x+=Math.max(0,Math.max(b.getX(h.y+c),d.getX(h.y-c))-(h.x-f));wade.setCameraPosition(h)},"_wade_isoConstrainCamera"):wade.setMainLoopCallback(null,"_wade_isoConstrainCamera")};this.spawnObjectNearObject=function(a,c,b,g,d,e,j){var a="string"==typeof a?
wade.getSceneObject(a).gridCoords:a.gridCoords,h;"undefined"==typeof g&&(g=-1);"undefined"==typeof d&&(d=-1);"undefined"==typeof e&&(e=1);for("undefined"==typeof j&&(j=1);g<=e;g++)for(var n=d;n<=j;n++)if(!this.collisionMap[a.x+g]||!this.collisionMap[a.x+g][a.z+n])h={x:a.x+g,z:a.z+n};return h?this.createObject(c,h,b):null};this.swapObjects=function(a,c){var b,d,e,j=a.iso.objectData.gridMap||[{x:0,z:0}],n=c.iso.objectData.gridMap||[{x:0,z:0}],h=a.iso.objectData.collisionMap,k=c.iso.objectData.collisionMap,
i=a.iso.gridCoords,l=c.iso.gridCoords;if(h)for(b=0;b<h.length;b++)d=h[b].x+i.x,e=h[b].z+i.z,this.collisionMap[d][e]=0;for(b=0;b<j.length;b++)d=j[b].x+i.x,e=j[b].z+i.z,wade.removeObjectFromArray(a,this.gridObjects[d][e]);if(k)for(b=0;b<k.length;b++)d=k[b].x+l.x,e=k[b].z+l.z,this.collisionMap[d][e]=0;for(b=0;b<n.length;b++)d=n[b].x+l.x,e=n[b].z+l.z,wade.removeObjectFromArray(c,this.gridObjects[d][e]);b=i;i=l;l=b;a.iso.gridCoords=i;c.iso.gridCoords=l;if(h)for(b=0;b<h.length;b++)d=h[b].x+i.x,e=h[b].z+
i.z,this.collisionMap[d]||(this.collisionMap[d]=[]),this.collisionMap[d][e]=a;for(b=0;b<j.length;b++)d=j[b].x+i.x,e=j[b].z+i.z,this.gridObjects[d]||(this.gridObjects[d]=[]),this.gridObjects[d][e]||(this.gridObjects[d][e]=[]),this.gridObjects[d][e].push(a);if(k)for(b=0;b<k.length;b++)d=k[b].x+l.x,e=k[b].z+l.z,this.collisionMap[d]||(this.collisionMap[d]=[]),this.collisionMap[d][e]=c;for(b=0;b<j.length;b++)d=j[b].x+i.x,e=j[b].z+i.z,this.gridObjects[d]||(this.gridObjects[d]=[]),this.gridObjects[d][e]||
(this.gridObjects[d][e]=[]),this.gridObjects[d][e].push(c);a.setPosition(g.getWorldCoordinates(i.x,i.z));c.setPosition(g.getWorldCoordinates(l.x,l.z))};this.findPath=function(a,b,c){var d,e=c?y(c):k,j=[],n=[a];a.gScore=0;a.hScore=Math.abs(a.x-b.x)+Math.abs(a.z-b.z);for(a.fScore=a.hScore;n.length;){var h=n[0].fScore,i=n[0];d=0;for(c=1;c<n.length;c++){var m=n[c],l=m.fScore;l<h&&(i=m,h=l,d=c)}if(i.x==b.x&&i.z==b.z){b=[];for(c=i;c.cameFrom;)b.push(c),c=c.cameFrom;b.push(a);a=[];for(c=0;c<b.length;c++)a.push(b[b.length-
1-c]);return a}wade.removeObjectFromArrayByIndex(d,n);j.push(i);for(c=0;c<e.length;c++)if(h=e[c],h={x:i.x+h.x,z:i.z+h.z},!(0>h.x||0>h.z||h.x>=g.numTilesX*g.c_numCellsPerTile||h.z>=g.numTilesZ*g.c_numCellsPerTile)&&(!this.collisionMap[h.x]||!this.collisionMap[h.x][h.z])){m=!1;for(d=0;d<j.length;d++)if(l=j[d],l.x==h.x&&l.z==h.z){m=!0;break}if(!m){m=i.gScore+1;l=!1;for(d=0;d<n.length;d++){var v=n[d];if(v.x==h.x&&v.z==h.z){l=!0;h=v;break}}d=!1;l?m<h.gScore&&(d=!0):(n.push(h),h.hScore=Math.abs(h.x-b.x)+
Math.abs(h.z-b.z),d=!0);d&&(h.cameFrom=i,h.gScore=m,h.fScore=h.gScore+h.hScore)}}}return[]};this.moveObjectToCell=function(a,b,c,d){if("string"==typeof a&&(a=wade.getSceneObject(a),!a))return!1;if(!d)return v(a,b,c)?(a.setPosition(g.getWorldCoordinates(b,c)),a.iso.targetCoords=0,wade.removeObjectFromArray(a,m),!0):!1;if(a.iso.gridCoords.x==b&&a.iso.gridCoords.z==c)return!0;a.iso.targetCoords={x:b,z:c};a.iso.previousPosition=a.getPosition();m.push(a);b=g.getWorldCoordinates(b,c);a.moveTo(b.x,b.y,d);
return!0};this.setTile=function(a,b,c){g.setTile(a,b,c)};this.setTransition=function(a,b,c){g.setTransition(a,b,c)};this.setDetail=function(a,b,c){g.setDetail(a,b,c)};this.getWorldCoordinates=function(a,b){return g.getWorldCoordinates(a,b)};this.getCellCoordinates=function(a,b){return g.getCellCoordinates(a,b)};this.getTileCoordinates=function(a,b){return g.getTileCoordinates(a,b)};this.getTileTextureAtCell=function(a,b){return g.getTileAtCell(a,b)};this.setHighlight=function(a,b){g.setHighlight(a,
b)};this.getObjectsInCell=function(a,b){var c=this.gridObjects[a]&&this.gridObjects[a][b];return c&&wade.cloneArray(c)||[]};this.sortTerrainTiles=function(){g.sort()};this.drawGrid=function(a){"undefined"==typeof a&&(a=!0);g.drawGrid(a)};this.draw_=function(a,b){b=b||"blue";return function(c){var d=this._position,g=this._size.x/2,e=this._size.y/2,j=c.strokeStyle,h=c.fillStyle;a&&(c.strokeStyle=a);c.fillStyle=b;c.beginPath();c.moveTo(d.x-g,d.y);c.lineTo(d.x,d.y+e);c.lineTo(d.x+g,d.y);c.lineTo(d.x,
d.y-e);j&&c.stroke();h&&c.fill();c.strokeStyle=j;c.fillStyle=h}};var v=function(a,c,d){if(a.iso.gridCoords.x==c&&a.iso.gridCoords.z==d)return!0;var g,e,j,n=a.iso.objectData.gridMap||[{x:0,z:0}],h=a.iso.objectData.collisionMap;if(h)for(g=0;g<h.length;g++)if(e=h[g].x+c,j=h[g].z+d,b.collisionMap[e]&&b.collisionMap[e][j])return!1;for(g=0;g<n.length;g++)e=n[g].x+a.iso.gridCoords.x,j=n[g].z+a.iso.gridCoords.z,wade.removeObjectFromArray(a,b.gridObjects[e][j]);if(h)for(g=0;g<h.length;g++)e=h[g].x+a.iso.gridCoords.x,
j=h[g].z+a.iso.gridCoords.z,b.collisionMap[e]&&b.collisionMap[e][j]&&(b.collisionMap[e][j]=0);for(g=0;g<n.length;g++)e=n[g].x+c,j=n[g].x+d,b.gridObjects[e]||(b.gridObjects[e]=[]),b.gridObjects[e][j]||(b.gridObjects[e][j]=[]),b.gridObjects[e][j].push(a);if(h)for(g=0;g<h.length;g++)e=h[g].x+c,j=h[g].z+d,b.collisionMap[e]||(b.collisionMap[e]=[]),b.collisionMap[e][j]=a;a.iso.gridCoords.x=c;a.iso.gridCoords.z=d;return!0},i=function(a,c){return function(){e[a]=1;e.terrain&&e.objects&&c&&c()}},y=function(a){switch(a){case "straight":return[{x:-1,
z:-1},{x:-1,z:1},{x:1,z:-1},{x:1,z:1}];case "diagonal":return[{x:0,z:-1},{x:0,z:1},{x:-1,z:0},{x:1,z:0}];case "both":return[{x:-1,z:-1},{x:-1,z:1},{x:1,z:-1},{x:1,z:1},{x:0,z:-1},{x:0,z:1},{x:-1,z:0},{x:1,z:0}]}return[]}};wade.iso=new Wade_iso;
function TerrainBehavior(){this.name="TerrainBehavior";this.tileSprites=[];this.tileData=[];this.gridSprites=[];this.transitionSprites=[];this.transitionData=[];this.detailSprites=[];this.detailData=[];this.c_tileSize={x:512,y:256};this.c_numCellsPerTile=4;this.c_origin={x:0,y:-this.c_tileSize.y/2};this.c_cellSize={x:this.c_tileSize.x/this.c_numCellsPerTile,y:this.c_tileSize.y/this.c_numCellsPerTile};this.numTilesZ=this.numTilesX=0;this.onAddToScene=function(){this.cellHighlightObjects=[];wade.addEventListener(this.owner,
"onMouseDown")};this.getCellHighlightObject=function(b){if(!this.cellHighlightObjects[b]){var c=new Sprite(this.highlightTexture,wade.iso.getTerrainLayerId());c.setSize(this.c_cellSize.x,this.c_cellSize.y);this.cellHighlightObjects[b]=new SceneObject(c,0,0,0);wade.addSceneObject(this.cellHighlightObjects[b])}return this.cellHighlightObjects[b]};this.hideCellHighlightObjects=function(){for(var b=0;b<this.cellHighlightObjects.length;b++)this.cellHighlightObjects[b].setVisible(!1)};this.loadData_begin=
function(b,c){this.finishedLoading_=!1;this.loadingList=[];var a={};this.completeRequests=0;var d,e;for(d=0;d<b.terrain.tileData.length;d++)e=b.terrain.tileData[d].texture,a[e]||(this.loadingList.push(e),a[e]=1);for(d=0;d<b.terrain.transitionData.length;d++)e=b.terrain.transitionData[d].texture,a[e]||(this.loadingList.push(e),a[e]=1);for(d=0;d<b.terrain.detailData.length;d++)e=b.terrain.detailData[d].texture,a[e]||(this.loadingList.push(e),a[e]=1);for(d=0;d<this.loadingList.length;d++)wade.loadImage(this.loadingList[d],
this.onLoadingRequestComplete_(b,c))};this.onLoadingRequestComplete_=function(b,c){var a=this;return function(){++a.completeRequests==a.loadingList.length&&(a.loadData_end(b),a.finishedLoading_=!0,c&&c())}};this.loadData_end=function(b){var c,a;this.numTilesX=b.terrain.numTilesX;this.numTilesZ=b.terrain.numTilesZ;for(c=0;c<this.numTilesX;c++){this.tileSprites[c]=[];this.tileData[c]=[];this.transitionSprites[c]=[];this.transitionData[c]=[];for(a=0;a<this.numTilesZ;a++){this.setTile(c,a,b.terrain.tileData[b.terrain.tileDataIds[c][a]]);
var d=b.terrain.transitionData[b.terrain.transitionDataIds[c][a]];d&&this.setTransition(c,a,d)}}for(c=0;c<this.numTilesX*this.c_numCellsPerTile;c++){this.detailSprites[c]=[];this.detailData[c]=[];for(a=0;a<this.numTilesZ*this.c_numCellsPerTile;a++)(d=b.terrain.detailData[b.terrain.detailDataIds[c][a]])&&this.setDetail(c,a,d)}};this.setNumTiles=function(b,c){var a,d;for(a=b;a<this.numTilesX;a++)for(d=0;d<this.numTilesZ;d++)this.tileSprites[a][d]=this.tileData[a][d]=this.transitionSprites[a][d]=this.transitionData[a][d]=
0;for(d=c;d<this.numTilesZ;d++)for(a=0;a<this.numTilesX;a++)this.tileSprites[a][d]=this.tileData[a][d]=this.transitionSprites[a][d]=this.transitionData[a][d]=0;for(a=b*this.c_numCellsPerTile;a<this.numTilesX*this.c_numCellsPerTile;a++)for(d=0;d<this.numTilesZ*this.c_numCellsPerTile;d++)this.detailSprites[a][d]=this.detailData[a][d]=0;for(d=c*this.c_numCellsPerTile;d<this.numTilesZ*this.c_numCellsPerTile;d++)for(a=0;a<this.numTilesX*this.c_numCellsPerTile;a++)this.detailSprites[a][d]=this.detailData[a][d]=
0;var e={texture:"_wade_isoDefault"};for(a=this.numTilesX;a<b;a++){this.tileSprites[a]=[];this.tileData[a]=[];this.transitionSprites[a]=[];this.transitionData[a]=[];for(d=0;d<c;d++)this.setTile(a,d,e)}for(d=this.numTilesZ;d<c;d++)for(a=0;a<this.numTilesX;a++)this.setTile(a,d,e);for(a=this.numTilesX*this.c_numCellsPerTile;a<b*this.c_numCellsPerTile;a++)this.detailSprites[a]=[],this.detailData[a]=[];this.numTilesX=b;this.numTilesZ=c};this.setTile=function(b,c,a){if(a){var d=!0,e=a.texture;if(a.rotation&&
(e+="_iso_rot_"+a.rotation,"ok"!=wade.getLoadingStatus(e))){var m=new Sprite(a.texture);m.setRotation(a.rotation*Math.PI/2);m.drawToImage(e,!0)}this.tileSprites[b][c]&&(a.animation||this.tileData[b][c].animation?(this.owner.removeSprite(this.tileSprites[b][c]),this.tileSprites[b][c]=0):(this.tileSprites[b][c].setImageFile(e),d=!1));d&&(m={x:this.c_origin.x+(b-c)*this.c_tileSize.x/2,y:this.c_origin.y-(b+c)*this.c_tileSize.y/2},a.animation?(d=new Sprite(0,wade.iso.getTerrainLayerId()),e=new Animation(e,
a.animation.numFrames.x,a.animation.numFrames.y,a.animation.speed,!0),d.addAnimation("default",e),d.playAnimation("default")):d=new Sprite(e,wade.iso.getTerrainLayerId()),d.setPosition(m),e=a.scale||1,d.setSize(this.c_tileSize.x*wade.iso.getTileScaleFactor()*e,this.c_tileSize.y*wade.iso.getTileScaleFactor()*e),d.customSortOrder=0,this.tileSprites[b][c]=d,this.owner.addSprite(d,m))}else this.tileSprites[b][c]&&this.owner.removeSprite(this.tileSprites[b][c]),this.tileSprites[b][c]=0;this.tileData[b][c]=
a};this.setTransition=function(b,c,a){if(a){var d=!0,e=a.texture;if(a.rotation&&(e+="_iso_rot_"+a.rotation,"ok"!=wade.getLoadingStatus(e))){var m=new Sprite(a.texture);m.setRotation(a.rotation*Math.PI/2);m.drawToImage(e,!0)}this.transitionSprites[b][c]&&(a.animation||this.transitionData[b][c].animation?(this.owner.removeSprite(this.transitionSprites[b][c]),this.transitionSprites[b][c]=0):(this.transitionSprites[b][c].setImageFile(e),d=!1));if(d){d=this.tileSprites[b][c].getPosition();m=this.tileSprites[b][c].getSize();
if(a.animation){var e=new Sprite(0,wade.iso.getTerrainLayerId()),s=new Animation(a.texture,a.animation.numFrames.x,a.animation.numFrames.y,a.animation.speed,!0);e.addAnimation("default",s);e.playAnimation("default")}else e=new Sprite(e,wade.iso.getTerrainLayerId());e.setPosition(d);s=a.scale||1;e.setSize(m.x*wade.iso.getTileScaleFactor()*s,m.y*wade.iso.getTileScaleFactor()*s);e.customSortOrder=1;this.owner.addSprite(e,d);this.transitionSprites[b][c]=e}}else this.transitionSprites[b][c]&&this.owner.removeSprite(this.transitionSprites[b][c]),
this.transitionSprites[b][c]=0;this.transitionData[b][c]=a};this.setDetail=function(b,c,a){if(a){var d=!0,e=a.texture;if(a.rotation&&(e+="_iso_rot_"+a.rotation,"ok"!=wade.getLoadingStatus(e))){var m=new Sprite(a.texture);m.setRotation(a.rotation*Math.PI/2);m.drawToImage(e,!0)}this.detailSprites[b][c]&&(a.animation||this.detailData[b][c].animation?(this.owner.removeSprite(this.transitionSprites[b][c]),this.transitionSprites[b][c]=0):(this.detailSprites[b][c].setImageFile(e),d=!1));d&&(d=this.getWorldCoordinates(b,
c),a.animation?(e=new Sprite(0,wade.iso.getTerrainLayerId()),m=new Animation(a.texture,a.animation.numFrames.x,a.animation.numFrames.y,a.animation.speed,!0),e.addAnimation("default",m),e.playAnimation("default")):e=new Sprite(e,wade.iso.getTerrainLayerId()),e.setPosition(d),m=a.scale||1,e.setSize(this.c_cellSize.x*wade.iso.getTileScaleFactor()*m,this.c_cellSize.y*wade.iso.getTileScaleFactor()*m),e.customSortOrder=2,this.owner.addSprite(e,d),this.detailSprites[b][c]=e)}else this.detailSprites[b][c]&&
this.owner.removeSprite(this.detailSprites[b][c]),this.detailSprites[b][c]=0;this.detailData[b][c]=a};this.getWorldCoordinates=function(b,c){return{x:(b-c)*this.c_cellSize.x/2,y:-(b+c+1)*this.c_cellSize.y/2}};this.getCellCoordinates=function(b,c){var a=b/this.c_cellSize.x-c/this.c_cellSize.y,d=-(b/this.c_cellSize.x+c/this.c_cellSize.y),a=Math.floor(a),d=Math.floor(d);return{x:a,z:d,valid:0<=a&&0<=d&&a<this.numTilesX*this.c_numCellsPerTile&&d<this.numTilesZ*this.c_numCellsPerTile}};this.getTileCoordinates=
function(b,c){var a=this.getCellCoordinates(b,c);return{x:Math.floor(a.x/this.c_numCellsPerTile),z:Math.floor(a.z/this.c_numCellsPerTile),valid:a.valid}};this.onMouseDown=function(b){if(wade.app.onTerrainClick&&(b=this.getCellCoordinates(b.position.x,b.position.y),b.valid)){var c=this.getWorldCoordinates(b.x,b.z);return wade.app.onTerrainClick({gridCoords:b,worldCoords:c})}return!1};this.getTileAtCell=function(b,c){var a=this.tileSprites[Math.floor(b/this.c_numCellsPerTile)][Math.floor(c/this.c_numCellsPerTile)];
return a?a.getImageName():""};this.setHighlight=function(b,c){this.highlightTexture=b;this.highlightOffsets=c||[{x:0,z:0}];if(this.highlightTexture&&this.highlightOffsets&&this.highlightOffsets.length){for(var a=0;a<this.cellHighlightObjects.length;a++)this.getCellHighlightObject(a).getSprite(0).setImageFile(b);this.owner.isListeningFor("onMouseMove")||this.owner.listenFor("onMouseMove")}else this.owner.stopListeningFor("onMouseMove"),this.hideCellHighlightObjects()};this.onMouseMove=function(b){var c,
b=this.getCellCoordinates(b.position.x,b.position.y);if(b.valid&&this.highlightTexture&&this.highlightOffsets&&this.highlightOffsets.length)for(var a=0;a<this.highlightOffsets.length;a++){c=this.highlightOffsets[a];c=this.getWorldCoordinates(b.x+c.x,b.z+c.z);var d=this.getCellHighlightObject(a);d.setPosition(c);d.setVisible(!0)}else this.hideCellHighlightObjects();return!0};this.sort=function(){wade.getLayer(wade.iso.getTerrainLayerId()).sort(function(b,c){var a=b.customSortOrder-c.customSortOrder;
if(a)return a;a=b.getPosition().y+b.getSortPoint().y*b.getSize().y-c.getPosition().y-c.getSortPoint().y*c.getSize().y;return Math.abs(a)<wade.c_epsilon?b.id-c.id:a})};this.drawGrid=function(b){var c,a=wade.iso.getTerrainLayerId();if(b&&!this.gridSprites.length)for(b=0;b<this.numTilesX;b++){this.gridSprites[b]=[];for(c=0;c<this.numTilesZ;c++){var d=new Sprite("_wade_isoGrid",a);d.customSortOrder=3;var e={x:this.c_origin.x+(b-c)*this.c_tileSize.x/2,y:this.c_origin.y-(b+c)*this.c_tileSize.y/2};d.setPosition(e);
d.setSize(this.c_tileSize.x*wade.iso.getTileScaleFactor(),this.c_tileSize.y*wade.iso.getTileScaleFactor());this.owner.addSprite(d,e);this.gridSprites[b][c]=d}}else if(!b&&this.gridSprites.length){for(b=0;b<this.numTilesX;b++)for(c=0;c<this.numTilesZ;c++)this.owner.removeSprite(this.gridSprites[b][c]);this.gridSprites.length=0}this.sort()}}
function IsoCharacter(){var b=this,c=[],a,d="forward",e,m;this.name="IsoCharacter";this.movementSpeed=160;this.setDestination=function(a){var c=this.owner.getPosition(),b=wade.iso.getCellCoordinates(c.x,c.y),d=this.getNextDestination();if(d){var e=d.x-b.x;e&&(e/=Math.abs(e));var i=d.z-b.z;i&&(i/=Math.abs(i));b.x+=e;b.z+=i}e=wade.iso.findPath(b,a,m);if(e.length){i=wade.iso.getWorldCoordinates(b.x,b.z);this.clearDestinations();if(Math.abs(c.x-i.x)>wade.c_epsilon||Math.abs(c.y-i.z)>wade.c_epsilon){if(d.x==
a.x&&d.z==a.z)return!1;s(b);this._goToNextDestination()}if(b.x==a.x&&b.z==a.z)return!1;for(c=1;c<e.length-1;c++)b=e[c].z-e[c-1].z,d=e[c+1].z-e[c].z,(e[c].x-e[c-1].x!=e[c+1].x-e[c].x||b!=d)&&s(e[c]);s(a);return!0}return!1};this.clearDestinations=function(){c.length=0};this.setMovementType=function(a){m=a};this.getNextDestination=function(){return this._nextDestination};this.setDirection=function(a){this.owner.isMoving()||this.owner.playAnimation("Idle_iso_"+a)};this.goToObject=function(a){if("string"==
typeof a&&(a=wade.getSceneObject(a),!a))return;var c=this.owner.iso.gridCoords,b=[],d=a.iso.objectData.interactionOffset;d&&b.push({x:a.iso.gridCoords.x+d.x,z:a.iso.gridCoords.z+d.z,object:a});b.push({x:a.iso.gridCoords.x,z:a.iso.gridCoords.z,object:a});for(var d=wade.iso.getValidMovementDirections(),e=[],i=0;i<d.length;i++)e.push({x:a.iso.gridCoords.x+d[i].x,z:a.iso.gridCoords.z+d[i].z,object:a});e.sort(function(a,b){var d,e;d=c.x-a.x;e=c.z-a.z;var g=d*d+e*e;d=c.x-b.x;e=c.z-b.z;return g-(d*d+e*e)});
for(i=0;i<e.length;i++)b.push(e[i]);for(i=0;i<b.length;i++)if(b[i].x!=c.x||b[i].z!=c.z){if(this.setDestination(b[i]))break}else{this.owner.processEvent("onMoveComplete");break}};this.startWandering=function(c,b,d){a={probability:c,stepDistance:b,targetObject:d}};this.stopWandering=function(){a=0};this.onMoveComplete=function(){if(c.length)this._goToNextDestination();else{this.owner.playAnimation("Idle_iso_"+this.lastDirection);this.lastDirection="";var a=this._nextDestination;this._nextDestination=
null;this.owner.processEvent("onDestinationReached",{destination:a});if(e){a=[{x:0,z:0}];e.interactionOffset&&a.push({x:-e.interactionOffset.x,z:-e.interactionOffset.z});for(var a=a.concat(wade.iso.getValidMovementDirections()),b=0;b<a.length;b++)for(var d=wade.iso.getObjectsInCell(this.owner.iso.gridCoords.x+a[b].x,this.owner.iso.gridCoords.z+a[b].z),k=0;k<d.length;k++)d[k]==e&&this.owner.processEvent("onObjectReached",{object:d[k]})}}};this.onAddToScene=function(){wade.addEventListener(this.owner,
"onAppTimer")};this.onAppTimer=function(){a&&Math.random()<a.probability&&this._wander();if(0.1>Math.random()){var b=this.owner.getSprite(0),c=b.getCurrentAnimationName(),e=c.indexOf("_variation_");0<=e&&(c=c.substr(0,e));for(var k=0;b.hasAnimation(c+"_variation_"+k);k++);k&&!b.getCurrentAnimation().isPlaying()&&(e&&"reverse"==d?c=b.getCurrentAnimationName():(c+="_variation_"+Math.floor(Math.random()*k),d="forward"),this.owner.playAnimation(c,d),d="forward"==d?"reverse":"forward")}};this._wander=
function(){if(!c.length){var b=this.owner.getGridCoords(),d=Math.round(2*Math.random()*a.stepDistance-a.stepDistance),e=Math.round(2*Math.random()*a.stepDistance-a.stepDistance);if(a&&a.targetObject){var k="string"==typeof a.targetObject?wade.getSceneObject(a.targetObject):a.targetObject;k&&(0.5>Math.random()&&0>(k.gridCoords.x-b.x)*d&&(d*=-1),0.5>Math.random()&&0>(k.gridCoords.z-b.z)*e&&(e*=-1))}if(d||e)b.x+=d,b.z+=e,wade.iso.checkCollisionsAtCell(b.x,b.z)||this.setDestination(b)}};this._goToNextDestination=
function(){var a=this.owner.iso.gridCoords,b=c[0];this._nextDestination=c[0];e=c[0].object;wade.removeObjectFromArrayByIndex(0,c);wade.iso.moveObjectToCell(this.owner,b.x,b.z,this.movementSpeed);var d=b.x-a.x,a=b.z-a.z;d&&(d/=Math.abs(d));a&&(a/=Math.abs(a));var k;switch(d.toString()+a){case "-1-1":k="s";break;case "-10":k="sw";break;case "-11":k="w";break;case "0-1":k="se";break;case "01":k="nw";break;case "1-1":k="e";break;case "10":k="ne";break;case "11":k="n"}k!=this.lastDirection&&(this.lastDirection=
k,this.owner.playAnimation("Walk_iso_"+this.lastDirection))};var s=function(a){c.push(a);b.owner.isMoving()||b._goToNextDestination()}};
